services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5432:5432"
